export const kitchenOption = [
  { value: "*", label: "Все страны и регионы" },
  { value: "Italian", label: "Italian" },
  { value: "Asian", label: "Asian" },
  { value: "Mexican", label: "Mexican" },
  { value: "American", label: "American" },
  { value: "Pakistani", label: "Pakistani" },
  { value: "Mediterranean", label: "Mediterranean" },
  { value: "Japanese", label: "Japanese" },
  { value: "Korean", label: "Korean" },
  { value: "Greek", label: "Greek" },
  { value: "Indian", label: "Indian" },
  { value: "Turkish", label: "Turkish" },
  { value: "Thai", label: "Thai" },
  { value: "Smoothie", label: "Smoothie" },
  { value: "Russian", label: "Russian" },
  { value: "Lebanese", label: "Lebanese" },
  { value: "Brazilian", label: "Brazilian" },
  { value: "Spanish", label: "Spanish" },
  { value: "Vietnamese", label: "Vietnamese" },
  { value: "Moroccan", label: "Moroccan" },
  { value: "Cocktail", label: "Cocktail" },
  { value: "Hawaiian", label: "Hawaiian" },
];

export const mealOptions = [
  { value: "*", label: "Все типы" },
  { value: "Dinner", label: "Dinner" },
  { value: "Lunch", label: "Lunch" },
  { value: "Snack", label: "Snack" },
  { value: "Dessert", label: "Dessert" },
  { value: "Side Dish", label: "Side Dish" },
  { value: "Appetizer", label: "Appetizer" },
  { value: "Snacks", label: "Snacks" },
  { value: "Breakfast", label: "Breakfast" },
  { value: "Beverage", label: "Beverage" },
];
